language: csharp
sudo: required
dist: ubuntu
mono: none
dotnet: 2.1
branches:
 - only:
   - master

before_script:
 - dotnet restore

script:
 - dotnet build
 - dotnet test

 after_success:
  - ssh student-admin@104.248.19.206
  - mkdir /var/www/student-notes/testtyy