language: csharp
sudo: required
dist: ubuntu
mono: none
dotnet: 2.1
branches:
 - only:
   - master

addons:
  ssh_known_hosts: $deploy_server_ip

before_script:
- dotnet restore
- dotnet build
- dotnet test
- mkdir $TRAVIS_BUILD_DIR/keye

script:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in deploy_id_rsa.enc -out $TRAVIS_BUILD_DIR/keye/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/keye/deploy_key
- echo -e "Host $deploy_server_ip\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add $TRAVIS_BUILD_DIR/keye/deploy_key
- ssh -i $TRAVIS_BUILD_DIR/keye/deploy_key $deploy_server_user@$deploy_server_ip /home/student-admin/build_student_notes_app.sh
- echo "END OF TRAVIS"
