language: csharp
sudo: required
dist: ubuntu
mono: none
dotnet: 2.1
branches:
 - only:
   - master

addons:
  ssh_known_hosts: $deploy_server_ip

before_script:
- dotnet restore
- dotnet build
- dotnet test

script:
- echo "START of Travis CI building server app"
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in deploy_id_rsa.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $deploy_server_ip\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key $deploy_server_user@$deploy_server_ip /home/student-admin/build_student_notes_app.sh
- mkdir $TRAVIS_BUILD_DIR/new_json_settings
- openssl aes-256-cbc -K $encrypted_bc678f3600cd_key -iv $encrypted_bc678f3600cd_iv -in appsettings_server.json.enc -out $TRAVIS_BUILD_DIR/new_json_settings/appsettings.json -d
- scp -i ./deploy_key $TRAVIS_BUILD_DIR/new_json_settings/appsettings.json $deploy_server_user@$deploy_server_ip:/var/www/student-notes/StudentNotes_MVC_SebastianPytel/appsettings.json
- echo "END of Travis CI building server app"
