language: csharp
sudo: required
dist: ubuntu
mono: none
dotnet: 2.1
branches:
 - only:
   - master

addons:
  ssh_known_hosts: $deploy_server_ip

before_script:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in deploy_id_rsa.enc -out /tmp/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa
- ssh-add /tmp/id_rsa

script:
  - provider: script
    skip_cleanup: true
    script: ssh $deploy_server_user@$deploy_server_ip
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: mkdir /var/www/student-notes/testtyy
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: 
    - git status
    - git status
    on:
      branch: master