language: csharp
sudo: required
dist: ubuntu
mono: none
dotnet: 2.1
branches:
 - only:
   - master

addons:
  ssh_known_hosts: $deploy_server_ip

script:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in deploy_id_rsa.enc -out $TRAVIS_BUILD_DIR/keye/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/keye/deploy_key
- echo -e "Host $deploy_server_ip\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add $TRAVIS_BUILD_DIR/keye/deploy_key
- rsync -r --quiet $TRAVIS_BUILD_DIR/keye <ssh-user>@<deploy-host>:/home/student-admin/wymiana
- mkdir /home/student-admin/test11 | ssh -i /tmp/id_rsa $deploy_server_user@$deploy_server_ip pwd
- ssh -i /tmp/id_rsa $deploy_server_user@$deploy_server_ip pwd < mkdir /home/student-admin/test22
- mkdir /var/www/student-notes/testtyy
- git status
- echo "git fetch > /dev/null 2>&1"
- echo "git pull"
